name: Functional Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Extract <script> and run tests
        run: |
          awk '/<script>/{flag=1;next}/<\/script>/{flag=0}flag' index.html > test.js
          node test.js
